from __future__ import annotations

# Transitional extraction of legacy_stores from app.py.
# The block is executed in the caller namespace to preserve legacy global lookup.
SOURCE = (
    'class NarArchiveParser:\n'
    '    def parse(self, zip_bytes: bytes) -> tuple[list[RaceRow], list[EntryRow]]:\n'
    '        race_rows = strip_header(read_csv_from_zip(zip_bytes, "_racelist.csv"))\n'
    '        horse_rows = strip_header(read_csv_from_zip(zip_bytes, "_horselist.csv"))\n'
    '\n'
    '        races: list[RaceRow] = []\n'
    '        for row in race_rows:\n'
    '            if len(row) < 33:\n'
    '                continue\n'
    '            corner_orders: list[dict[int, int]] = []\n'
    '            for i in range(8):\n'
    '                idx = RACE_IDX["corner_order_start"] + i\n'
    '                if idx < len(row) and _clean(row[idx]):\n'
    '                    corner_orders.append(parse_corner_order(row[idx]))\n'
    '            races.append(\n'
    '                RaceRow(\n'
    '                    track=_clean(row[RACE_IDX["track"]]),\n'
    '                    date=_iso_date(row[RACE_IDX["date"]]),\n'
    '                    race_no=_int(row[RACE_IDX["race_no"]]),\n'
    '                    start_time=_start_time(row[RACE_IDX["start_time"]]),\n'
    '                    title=_clean(row[RACE_IDX["title"]]),\n'
    '                    distance=_int(row[RACE_IDX["distance"]]),\n'
    '                    weather=_normalize_weather(row[RACE_IDX["weather"]]),\n'
    '                    condition=_normalize_condition(row[RACE_IDX["condition"]]),\n'
    '                    field_size=_int(row[RACE_IDX["field_size"]]),\n'
    '                    prize=tuple(_int(row[RACE_IDX[f"prize{i}"]]) for i in range(1, 6)),\n'
    '                    corners=corner_orders,\n'
    '                )\n'
    '            )\n'
    '\n'
    '        entries: list[EntryRow] = []\n'
    '        for row in horse_rows:\n'
    '            if len(row) < 19:\n'
    '                continue\n'
    '            entries.append(\n'
    '                EntryRow(\n'
    '                    track=_clean(row[HORSE_IDX["track"]]),\n'
    '                    date=_iso_date(row[HORSE_IDX["date"]]),\n'
    '                    race_no=_int(row[HORSE_IDX["race_no"]]),\n'
    '                    frame_no=_int(row[HORSE_IDX["frame_no"]]),\n'
    '                    horse_no=_int(row[HORSE_IDX["horse_no"]]),\n'
    '                    name=_clean(row[HORSE_IDX["name"]]),\n'
    '                    sex=_normalize_sex(row[HORSE_IDX["sex"]]),\n'
    '                    age=_int(row[HORSE_IDX["age"]]),\n'
    '                    jockey=_clean(row[HORSE_IDX["jockey"]]),\n'
    '                    carried_weight=_carried_weight(row[HORSE_IDX["carried_weight"]]),\n'
    '                    trainer=_clean(row[HORSE_IDX["trainer"]]),\n'
    '                    finish=_int(row[HORSE_IDX["finish"]]) if len(row) > HORSE_IDX["finish"] else 0,\n'
    '                    time_seconds=_time_seconds(row[HORSE_IDX["time"]]) if len(row) > HORSE_IDX["time"] else 0,\n'
    '                )\n'
    '            )\n'
    '        return races, entries\n'
    '\n'
    '\n'
    'class NarStore:\n'
    '    def __init__(self, path: Path = DB_PATH):\n'
    '        self.path = path\n'
    '        path.parent.mkdir(parents=True, exist_ok=True)\n'
    '        self.conn = sqlite3.connect(path)\n'
    '        self.conn.row_factory = sqlite3.Row\n'
    '        self._migrate()\n'
    '\n'
    '    def _migrate(self) -> None:\n'
    '        self.conn.executescript(\n'
    '            """\n'
    '            PRAGMA journal_mode=WAL;\n'
    '            CREATE TABLE IF NOT EXISTS races (\n'
    '                track TEXT NOT NULL,\n'
    '                date TEXT NOT NULL,\n'
    '                race_no INTEGER NOT NULL,\n'
    "                start_time TEXT NOT NULL DEFAULT '',\n"
    "                scheduled_start_time TEXT NOT NULL DEFAULT '',\n"
    "                title TEXT NOT NULL DEFAULT '',\n"
    '                distance INTEGER NOT NULL DEFAULT 0,\n'
    "                weather TEXT NOT NULL DEFAULT '不明',\n"
    "                condition TEXT NOT NULL DEFAULT '不明',\n"
    '                field_size INTEGER NOT NULL DEFAULT 0,\n'
    '                prize1 INTEGER NOT NULL DEFAULT 0,\n'
    '                prize2 INTEGER NOT NULL DEFAULT 0,\n'
    '                prize3 INTEGER NOT NULL DEFAULT 0,\n'
    '                prize4 INTEGER NOT NULL DEFAULT 0,\n'
    '                prize5 INTEGER NOT NULL DEFAULT 0,\n'
    "                corners_json TEXT NOT NULL DEFAULT '[]',\n"
    '                PRIMARY KEY(track, date, race_no)\n'
    '            );\n'
    '            CREATE TABLE IF NOT EXISTS entries (\n'
    '                track TEXT NOT NULL,\n'
    '                date TEXT NOT NULL,\n'
    '                race_no INTEGER NOT NULL,\n'
    '                frame_no INTEGER NOT NULL DEFAULT 0,\n'
    '                horse_no INTEGER NOT NULL,\n'
    '                name TEXT NOT NULL,\n'
    "                sex TEXT NOT NULL DEFAULT '牡',\n"
    '                age INTEGER NOT NULL DEFAULT 0,\n'
    '                carried_weight REAL NOT NULL DEFAULT 0,\n'
    "                jockey TEXT NOT NULL DEFAULT '',\n"
    "                trainer TEXT NOT NULL DEFAULT '',\n"
    "                status TEXT NOT NULL DEFAULT '',\n"
    '                finish INTEGER NOT NULL DEFAULT 0,\n'
    '                time_seconds REAL NOT NULL DEFAULT 0,\n'
    "                corner_positions_json TEXT NOT NULL DEFAULT '[]',\n"
    '                PRIMARY KEY(track, date, race_no, horse_no)\n'
    '            );\n'
    '            CREATE INDEX IF NOT EXISTS idx_entries_name_date ON entries(name, date);\n'
    '            CREATE INDEX IF NOT EXISTS idx_entries_jockey_date ON entries(jockey, date);\n'
    '            CREATE INDEX IF NOT EXISTS idx_entries_trainer_date ON entries(trainer, date);\n'
    '            CREATE TABLE IF NOT EXISTS sync_log (\n'
    '                cache_key TEXT PRIMARY KEY,\n'
    '                synced_at INTEGER NOT NULL,\n'
    "                archive_path TEXT NOT NULL DEFAULT ''\n"
    '            );\n'
    '            """\n'
    '        )\n'
    '        race_cols = {row[1] for row in self.conn.execute("PRAGMA table_info(races)").fetchall()}\n'
    '        if "scheduled_start_time" not in race_cols:\n'
    '            self.conn.execute("ALTER TABLE races ADD COLUMN scheduled_start_time TEXT NOT NULL DEFAULT \'\'")\n'
    '        entry_cols = {row[1] for row in self.conn.execute("PRAGMA table_info(entries)").fetchall()}\n'
    '        if "status" not in entry_cols:\n'
    '            self.conn.execute("ALTER TABLE entries ADD COLUMN status TEXT NOT NULL DEFAULT \'\'")\n'
    '        self.conn.execute("UPDATE races SET scheduled_start_time=start_time WHERE scheduled_start_time=\'\'")\n'
    '        self.conn.commit()\n'
    '\n'
    '    def import_rows(self, races: Iterable[RaceRow], entries: Iterable[EntryRow]) -> None:\n'
    '        races = list(races)\n'
    '        race_lookup = {(r.track, r.date, r.race_no): r for r in races}\n'
    '        with self.conn:\n'
    '            for r in races:\n'
    '                self.conn.execute(\n'
    '                    """\n'
    '                    INSERT INTO races(track,date,race_no,start_time,scheduled_start_time,title,distance,weather,condition,field_size,\n'
    '                                      prize1,prize2,prize3,prize4,prize5,corners_json)\n'
    '                    VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)\n'
    '                    ON CONFLICT(track,date,race_no) DO UPDATE SET\n'
    '                      start_time=excluded.start_time,title=excluded.title,distance=excluded.distance,\n'
    "                      weather=CASE WHEN excluded.weather NOT IN ('','不明') THEN excluded.weather ELSE races.weather END,\n"
    "                      condition=CASE WHEN excluded.condition NOT IN ('','不明') THEN excluded.condition ELSE races.condition END,\n"
    '                      field_size=excluded.field_size,\n'
    '                      prize1=excluded.prize1,prize2=excluded.prize2,prize3=excluded.prize3,\n'
    '                      prize4=excluded.prize4,prize5=excluded.prize5,corners_json=excluded.corners_json\n'
    '                    """,\n'
    '                    (\n'
    '                        r.track, r.date, r.race_no, r.start_time, r.start_time, r.title, r.distance, r.weather, r.condition,\n'
    '                        r.field_size, *r.prize,\n'
    '                        json.dumps([{str(k): v for k, v in c.items()} for c in r.corners], ensure_ascii=False),\n'
    '                    ),\n'
    '                )\n'
    '            for e in entries:\n'
    '                race = race_lookup.get((e.track, e.date, e.race_no))\n'
    '                corners: list[int] = []\n'
    '                if race:\n'
    '                    for c in race.corners:\n'
    '                        if e.horse_no in c:\n'
    '                            corners.append(c[e.horse_no])\n'
    '                self.conn.execute(\n'
    '                    """\n'
    '                    INSERT INTO entries(track,date,race_no,frame_no,horse_no,name,sex,age,carried_weight,\n'
    '                                        jockey,trainer,status,finish,time_seconds,corner_positions_json)\n'
    '                    VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)\n'
    '                    ON CONFLICT(track,date,race_no,horse_no) DO UPDATE SET\n'
    '                      frame_no=excluded.frame_no,name=excluded.name,sex=excluded.sex,age=excluded.age,\n'
    '                      carried_weight=excluded.carried_weight,jockey=excluded.jockey,trainer=excluded.trainer,\n'
    "                      status=CASE WHEN entries.status<>'' THEN entries.status ELSE excluded.status END,\n"
    '                      finish=excluded.finish,time_seconds=excluded.time_seconds,\n'
    '                      corner_positions_json=excluded.corner_positions_json\n'
    '                    """,\n'
    '                    (\n'
    '                        e.track, e.date, e.race_no, e.frame_no, e.horse_no, e.name, e.sex, e.age,\n'
    '                        e.carried_weight, e.jockey, e.trainer, "", e.finish, e.time_seconds,\n'
    '                        json.dumps(corners, ensure_ascii=False),\n'
    '                    ),\n'
    '                )\n'
    '\n'
    '    def mark_synced(self, cache_key: str, archive_path: Path) -> None:\n'
    '        with self.conn:\n'
    '            self.conn.execute(\n'
    '                "INSERT OR REPLACE INTO sync_log(cache_key,synced_at,archive_path) VALUES(?,?,?)",\n'
    '                (cache_key, int(time.time()), str(archive_path)),\n'
    '            )\n'
    '\n'
    '    def synced_at(self, cache_key: str) -> int | None:\n'
    '        row = self.conn.execute("SELECT synced_at FROM sync_log WHERE cache_key=?", (cache_key,)).fetchone()\n'
    '        return int(row[0]) if row else None\n'
    '\n'
    '    def stats(self, role: str, name: str, cutoff: str) -> dict[str, int]:\n'
    '        if role not in {"jockey", "trainer"} or not name:\n'
    '            return {"starts": 0, "wins": 0, "seconds": 0, "thirds": 0}\n'
    '        row = self.conn.execute(\n'
    '            f"""\n'
    '            SELECT COUNT(*) starts,\n'
    '                   SUM(CASE WHEN finish=1 THEN 1 ELSE 0 END) wins,\n'
    '                   SUM(CASE WHEN finish=2 THEN 1 ELSE 0 END) seconds,\n'
    '                   SUM(CASE WHEN finish=3 THEN 1 ELSE 0 END) thirds\n'
    '            FROM entries WHERE {role}=? AND date<? AND finish>0\n'
    '            """,\n'
    '            (name, cutoff),\n'
    '        ).fetchone()\n'
    '        return {k: int(row[k] or 0) for k in ("starts", "wins", "seconds", "thirds")}\n'
    '\n'
    '    def role_profile(self, role: str, name: str, cutoff: str, track: str, distance: int, condition: str) -> dict:\n'
    '        """Condition-aware jockey/trainer record available strictly before the target race."""\n'
    '        if role not in {"jockey", "trainer"} or not name:\n'
    '            return {"overall": 0.5, "track": 0.5, "distance": 0.5, "condition": 0.5,\n'
    '                    "leaderRate": 0.0, "early3Rate": 0.0, "starts": 0}\n'
    '        rows = self.conn.execute(\n'
    '            f"""\n'
    '            SELECT e.finish, e.corner_positions_json, r.track, r.distance, r.condition\n'
    '            FROM entries e\n'
    '            JOIN races r ON r.track=e.track AND r.date=e.date AND r.race_no=e.race_no\n'
    '            WHERE e.{role}=? AND e.date<? AND e.finish>0\n'
    '            ORDER BY e.date DESC, e.race_no DESC\n'
    '            LIMIT 400\n'
    '            """,\n'
    '            (name, cutoff),\n'
    '        ).fetchall()\n'
    '\n'
    '        def rate(subset):\n'
    '            if not subset:\n'
    '                return 0.5\n'
    '            top3 = sum(1 for x in subset if 0 < int(x["finish"] or 0) <= 3)\n'
    '            return top3 / len(subset)\n'
    '\n'
    '        track_rows = [x for x in rows if (x["track"] or "") == track]\n'
    '        dist_rows = [x for x in rows if abs(int(x["distance"] or 0) - int(distance or 0)) <= 200]\n'
    '        cond_rows = [x for x in rows if condition and condition != "不明" and (x["condition"] or "") == condition]\n'
    '        lead = early3 = valid = 0\n'
    '        for x in rows[:120]:\n'
    '            try:\n'
    '                pos = json.loads(x["corner_positions_json"] or "[]")\n'
    '            except Exception:\n'
    '                pos = []\n'
    '            if not pos:\n'
    '                continue\n'
    '            first = _int(str(pos[0]))\n'
    '            if first <= 0:\n'
    '                continue\n'
    '            valid += 1\n'
    '            if first == 1:\n'
    '                lead += 1\n'
    '            if first <= 3:\n'
    '                early3 += 1\n'
    '        return {\n'
    '            "overall": rate(rows),\n'
    '            "track": rate(track_rows),\n'
    '            "distance": rate(dist_rows),\n'
    '            "condition": rate(cond_rows),\n'
    '            "leaderRate": (lead / valid) if valid else 0.0,\n'
    '            "early3Rate": (early3 / valid) if valid else 0.0,\n'
    '            "starts": len(rows),\n'
    '        }\n'
    '\n'
    '    def prize_before(self, horse_name: str, cutoff: str) -> int:\n'
    '        row = self.conn.execute(\n'
    '            """\n'
    '            SELECT COALESCE(SUM(CASE e.finish\n'
    '                WHEN 1 THEN r.prize1 WHEN 2 THEN r.prize2 WHEN 3 THEN r.prize3\n'
    '                WHEN 4 THEN r.prize4 WHEN 5 THEN r.prize5 ELSE 0 END), 0) AS prize\n'
    '            FROM entries e\n'
    '            JOIN races r ON r.track=e.track AND r.date=e.date AND r.race_no=e.race_no\n'
    'WHERE e.name=? AND e.date<? AND e.finish>0\n'
    '            """,\n'
    '            (horse_name, cutoff),\n'
    '        ).fetchone()\n'
    '        return int(row["prize"] or 0)\n'
    '\n'
    '    def recent_races(self, horse_name: str, cutoff: str, limit: int = 5) -> list[dict]:\n'
    '        rows = self.conn.execute(\n'
    '            """\n'
    '            SELECT e.*, r.title, r.distance, r.weather, r.condition, r.field_size, r.prize1\n'
    '            FROM entries e\n'
    '            JOIN races r ON r.track=e.track AND r.date=e.date AND r.race_no=e.race_no\n'
    '            WHERE e.name=? AND e.date<? AND e.finish>0\n'
    '            ORDER BY e.date DESC, e.race_no DESC\n'
    '            LIMIT ?\n'
    '            """,\n'
    '            (horse_name, cutoff, limit),\n'
    '        ).fetchall()\n'
    '        return [\n'
    '            {\n'
    '                "date": row["date"],\n'
    '                "track": row["track"],\n'
    '                "raceNumber": int(row["race_no"] or 0),\n'
    '                "raceId": f"nar-{row[\'date\']}-{row[\'track\']}-{int(row[\'race_no\'] or 0):02d}",\n'
    '                "title": row["title"] or f"{int(row[\'race_no\'] or 0)}R",\n'
    '                "distance": int(row["distance"] or 0),\n'
    '                "condition": row["condition"] or "不明",\n'
    '                "weather": row["weather"] or "不明",\n'
    '                "finish": int(row["finish"] or 0),\n'
    '                "timeSeconds": float(row["time_seconds"] or 0),\n'
    '                "cornerPositions": json.loads(row["corner_positions_json"] or "[]"),\n'
    '                "fieldSize": int(row["field_size"] or 0),\n'
    '                "racePrize1": int(row["prize1"] or 0),\n'
    '                "carriedWeight": float(row["carried_weight"] or 0),\n'
    '                "jockey": row["jockey"] or "",\n'
    '                "trainer": row["trainer"] or "",\n'
    '            }\n'
    '            for row in rows\n'
    '        ]\n'
    '\n'
    '    def races_json(self, iso_date: str) -> list[dict]:\n'
    '        race_rows = self.conn.execute(\n'
    '            "SELECT * FROM races WHERE date=? ORDER BY track, race_no", (iso_date,)\n'
    '        ).fetchall()\n'
    '        result: list[dict] = []\n'
    '        for race in race_rows:\n'
    '            entries = self.conn.execute(\n'
    '                "SELECT * FROM entries WHERE track=? AND date=? AND race_no=? ORDER BY horse_no",\n'
    '                (race["track"], iso_date, race["race_no"]),\n'
    '            ).fetchall()\n'
    '            if not entries:\n'
    '                continue\n'
    '            horses = []\n'
    '            for e in entries:\n'
    '                horses.append(\n'
    '                    {\n'
    '                        "id": _stable_id(iso_date, race["track"], race["race_no"], e["horse_no"], e["name"]),\n'
    '                        "horseNumber": int(e["horse_no"]),\n'
    '                        "frameNumber": int(e["frame_no"] or 0),\n'
    '                        "name": e["name"],\n'
    '                        "age": int(e["age"] or 0),\n'
    '                        "sex": e["sex"] or "牡",\n'
    '                        "carriedWeight": float(e["carried_weight"] or 0),\n'
    '                        "jockey": e["jockey"] or "",\n'
    '                        "trainer": e["trainer"] or "",\n'
    '                        "jockeyStats": self.stats("jockey", e["jockey"], iso_date),\n'
    '                        "trainerStats": self.stats("trainer", e["trainer"], iso_date),\n'
    '                        "jockeyProfile": self.role_profile("jockey", e["jockey"], iso_date, race["track"], int(race["distance"] or 0), race["condition"] or "不明"),\n'
    '                        "trainerProfile": self.role_profile("trainer", e["trainer"], iso_date, race["track"], int(race["distance"] or 0), race["condition"] or "不明"),\n'
    '                        "prizeMoneyAtRace": self.prize_before(e["name"], iso_date),\n'
    '                        "recentRaces": self.recent_races(e["name"], iso_date, 5),\n'
    '                    }\n'
    '                )\n'
    '            finishers = []\n'
    '            for e in entries:\n'
    '                fin = int(e["finish"] or 0)\n'
    '                if fin > 0:\n'
    '                    finishers.append({\n'
    '                        "finish": fin,\n'
    '                        "horseNumber": int(e["horse_no"]),\n'
    '                        "frameNumber": int(e["frame_no"] or 0),\n'
    '                        "name": e["name"],\n'
    '                        "timeSeconds": float(e["time_seconds"] or 0),\n'
    '                        "cornerPositions": json.loads(e["corner_positions_json"] or "[]"),\n'
    '                    })\n'
    '            finishers.sort(key=lambda x: (x["finish"], x["horseNumber"]))\n'
    '            need = min(3, len(entries))\n'
    '            ranks = {x["finish"] for x in finishers}\n'
    '            finalized = need > 0 and all(i in ranks for i in range(1, need + 1))\n'
    '            result_obj = {"status": "確定", "finishers": finishers} if finalized else None\n'
    '            result.append(\n'
    '                {\n'
    '                    "id": f"nar-{iso_date}-{race[\'track\']}-{int(race[\'race_no\']):02d}",\n'
    '                    "circuit": "地方",\n'
    '                    "date": iso_date,\n'
    '                    "track": race["track"],\n'
    '                    "raceNumber": int(race["race_no"]),\n'
    '                    "title": race["title"] or f"{int(race[\'race_no\'])}R",\n'
    '                    "distance": int(race["distance"] or 0),\n'
    '                    "condition": race["condition"] or "不明",\n'
    '                    "weather": race["weather"] or "不明",\n'
    '                    "fieldSize": int(race["field_size"] or len(entries)),\n'
    '                    "racePrize1": int(race["prize1"] or 0),\n'
    '                    "surface": "",\n'
    '                    "startTime": race["start_time"] or "",\n'
    '                    "scheduledStartTime": race["scheduled_start_time"] or race["start_time"] or "",\n'
    '                    "startTimeChanged": bool((race["scheduled_start_time"] or "") and (race["start_time"] or "") and race["scheduled_start_time"] != race["start_time"]),\n'
    '                    "horses": horses,\n'
    '                    "result": result_obj,\n'
    '                    "source": "NAR公式",\n'
    '                }\n'
    '            )\n'
    '        return result\n'
    '\n'
    '    def coverage(self) -> dict:\n'
    '        row = self.conn.execute("SELECT MIN(date) min_date, MAX(date) max_date FROM races").fetchone()\n'
    '        return {"minDate": row["min_date"], "maxDate": row["max_date"]}\n'
    '\n'
    '\n'
    'class NarSync:\n'
    '    def __init__(self, store: NarStore | None = None, parser: NarArchiveParser | None = None):\n'
    '        self.store = store or NarStore()\n'
    '        self.parser = parser or NarArchiveParser()\n'
    '        ARCHIVE_DIR.mkdir(parents=True, exist_ok=True)\n'
    '\n'
    '    def _download(self, url: str, destination: Path) -> bytes:\n'
    '        request = urllib.request.Request(\n'
    '            url,\n'
    '            headers={\n'
    '                "User-Agent": "Mozilla/5.0 (iPhone; CPU iPhone OS 18_0 like Mac OS X) AppleWebKit/605.1.15 Version/18.0 Mobile/15E148 Safari/604.1",\n'
    '                "Accept": "application/zip,application/octet-stream,*/*",\n'
    '                "Referer": "https://www.keiba.go.jp/KeibaWeb/TodayRaceInfo/TodayRaceInfoTop",\n'
    '                "Accept-Language": "ja-JP,ja;q=0.9",\n'
    '            },\n'
    '        )\n'
    '        with urllib.request.urlopen(request, timeout=45) as response:\n'
    '            data = response.read()\n'
    '        if not zipfile.is_zipfile(io.BytesIO(data)):\n'
    '            raise RuntimeError("NAR response was not a ZIP archive")\n'
    '        destination.parent.mkdir(parents=True, exist_ok=True)\n'
    '        destination.write_bytes(data)\n'
    '        return data\n'
    '\n'
    '    def import_zip_bytes(self, data: bytes, cache_key: str, archive_path: Path) -> dict:\n'
    '        races, entries = self.parser.parse(data)\n'
    '        self.store.import_rows(races, entries)\n'
    '        self.store.mark_synced(cache_key, archive_path)\n'
    '        return {"races": len(races), "entries": len(entries), "cacheKey": cache_key}\n'
    '\n'
    '    def sync_daily(self, force: bool = False) -> dict:\n'
    '        cache_key = "daily"\n'
    '        synced = self.store.synced_at(cache_key)\n'
    '        ttl = int(os.getenv("NAR_DAILY_TTL_SECONDS", "120"))\n'
    '        if not force and synced and int(time.time()) - synced < ttl:\n'
    '            return {"status": "cached", "cacheKey": cache_key}\n'
    '        dest = ARCHIVE_DIR / "daily_race.zip"\n'
    '        data = self._download(NAR_DAILY_RACE_URL, dest)\n'
    '        info = self.import_zip_bytes(data, cache_key, dest)\n'
    '        return {"status": "synced", **info}\n'
    '\n'
    '    def sync_month(self, year: int, month: int, force: bool = False) -> dict:\n'
    '        if not 1 <= month <= 12:\n'
    '            raise ValueError("month must be 1...12")\n'
    '        cache_key = f"month-{year:04d}-{month:02d}"\n'
    '        synced = self.store.synced_at(cache_key)\n'
    '        today = datetime.now().date()\n'
    '        is_current_month = (year == today.year and month == today.month)\n'
    '        current_ttl = int(os.getenv("NAR_CURRENT_MONTH_TTL_SECONDS", "300"))\n'
    '        if not force and synced:\n'
    '            age = int(time.time()) - synced\n'
    '            if (not is_current_month) or age < current_ttl:\n'
    '                return {"status": "cached", "cacheKey": cache_key}\n'
    '        dest = ARCHIVE_DIR / f"{year:04d}{month:02d}_race.zip"\n'
    '        url = NAR_MONTHLY_RACE_URL.format(year=year, month=month)\n'
    '        data = self._download(url, dest)\n'
    '        info = self.import_zip_bytes(data, cache_key, dest)\n'
    '        return {"status": "synced", **info}\n'
    '\n'
    '    def import_file(self, path: Path, cache_key: str | None = None) -> dict:\n'
    '        data = path.read_bytes()\n'
    '        key = cache_key or f"file-{path.name}-{int(path.stat().st_mtime)}"\n'
    '        return self.import_zip_bytes(data, key, path)\n'
    '\n'
    '\n'
    '\n'
    'CENTRAL_DB_PATH = DATA_ROOT / "central" / "central.sqlite3"\n'
    '\n'
    'class CentralStore:\n'
    '    def __init__(self, path: Path = CENTRAL_DB_PATH):\n'
    '        self.path = path\n'
    '        path.parent.mkdir(parents=True, exist_ok=True)\n'
    '        self.conn = sqlite3.connect(path)\n'
    '        self.conn.row_factory = sqlite3.Row\n'
    '        self.conn.execute("""\n'
    '            CREATE TABLE IF NOT EXISTS central_races(\n'
    '              id TEXT PRIMARY KEY,\n'
    '              date TEXT NOT NULL,\n'
    '              track TEXT NOT NULL,\n'
    '              race_no INTEGER NOT NULL,\n'
    '              payload TEXT NOT NULL,\n'
    '              updated_at INTEGER NOT NULL\n'
    '            )\n'
    '        """)\n'
    '        self.conn.execute("CREATE INDEX IF NOT EXISTS idx_central_date ON central_races(date,track,race_no)")\n'
    '        self.conn.commit()\n'
    '\n'
    '    def upsert(self, rows: list[dict]) -> int:\n'
    '        n = 0\n'
    '        with self.conn:\n'
    '            for raw in rows:\n'
    '                incoming = normalize_central_race(raw)\n'
    '                if not incoming:\n'
    '                    continue\n'
    '                old_row=self.conn.execute("SELECT payload FROM central_races WHERE id=?",(incoming["id"],)).fetchone()\n'
    '                if old_row:\n'
    '                    try:old=json.loads(old_row["payload"])\n'
    '                    except Exception:old={}\n'
    '                    merged=dict(old) if isinstance(old,dict) else {}\n'
    '                    # Lightweight schedule rows must never erase a prepared card/result.\n'
    '                    for k,v in incoming.items():\n'
    '                        if k=="horses":\n'
    '                            if isinstance(v,list) and v:merged[k]=v\n'
    '                            continue\n'
    '                        if k=="result":\n'
    '                            if isinstance(v,dict) and v:merged[k]=v\n'
    '                            continue\n'
    '                        if k in {"weather","condition"}:\n'
    '                            if v not in (None,"","不明"):merged[k]=v\n'
    '                            elif k not in merged:merged[k]="不明"\n'
    '                            continue\n'
    '                        if k=="fieldSize":\n'
    '                            if int(v or 0)>0:merged[k]=int(v)\n'
    '                            continue\n'
    '                        if v not in (None,"",0,[]):\n'
    '                            merged[k]=v\n'
    '                        elif k not in merged:\n'
    '                            merged[k]=v\n'
    '                    r=normalize_central_race(merged) or incoming\n'
    '                else:\n'
    '                    r=incoming\n'
    '                self.conn.execute(\n'
    '                    """INSERT INTO central_races(id,date,track,race_no,payload,updated_at)\n'
    '                       VALUES(?,?,?,?,?,?)\n'
    '                       ON CONFLICT(id) DO UPDATE SET date=excluded.date,track=excluded.track,\n'
    '                         race_no=excluded.race_no,payload=excluded.payload,updated_at=excluded.updated_at""",\n'
    '                    (r["id"], r["date"], r["track"], r["raceNumber"], json.dumps(r, ensure_ascii=False), int(time.time())),\n'
    '                )\n'
    '                n += 1\n'
    '        return n\n'
    '\n'
    '    def races_json(self, iso_date: str) -> list[dict]:\n'
    '        rows = self.conn.execute("SELECT payload FROM central_races WHERE date=? ORDER BY track,race_no", (iso_date,)).fetchall()\n'
    '        return [json.loads(x["payload"]) for x in rows]\n'
    '\n'
    '    def coverage(self) -> dict:\n'
    '        row = self.conn.execute("SELECT MIN(date) min_date, MAX(date) max_date, COUNT(*) cnt FROM central_races").fetchone()\n'
    '        return {"minDate": row["min_date"], "maxDate": row["max_date"], "count": int(row["cnt"] or 0)}\n'
)

def install_legacy_stores(namespace: dict) -> None:
    code = compile(SOURCE, '<arvexq:legacy_stores>', 'exec')
    exec(code, namespace, namespace)
