from __future__ import annotations

# Transitional extraction of race_stores from app.py.
# The block is executed in the caller namespace to preserve legacy global lookup.
SOURCE = (
    'class PreparedRaceStore:\n'
    '    def __init__(self, path: Path = PREPARED_DB_PATH):\n'
    '        self.path = path\n'
    '        self.path.parent.mkdir(parents=True, exist_ok=True)\n'
    '        conn = sqlite3.connect(self.path, timeout=3)\n'
    '        try:\n'
    '            conn.execute("PRAGMA journal_mode=WAL")\n'
    '            conn.execute(\n'
    '                """\n'
    '                CREATE TABLE IF NOT EXISTS prepared_races (\n'
    '                    race_id TEXT PRIMARY KEY,\n'
    "                    race_date TEXT NOT NULL DEFAULT '',\n"
    "                    circuit TEXT NOT NULL DEFAULT '',\n"
    '                    updated_at INTEGER NOT NULL,\n'
    '                    payload TEXT NOT NULL\n'
    '                )\n'
    '                """\n'
    '            )\n'
    '            conn.execute("CREATE INDEX IF NOT EXISTS idx_prepared_date ON prepared_races(race_date, circuit)")\n'
    '            conn.execute("CREATE TABLE IF NOT EXISTS horse_snapshots(race_id TEXT,horse_no INTEGER,payload TEXT NOT NULL,PRIMARY KEY(race_id,horse_no))")\n'
    '            conn.execute("CREATE VIEW IF NOT EXISTS race_snapshot AS SELECT * FROM prepared_races")\n'
    '            conn.execute("CREATE VIEW IF NOT EXISTS horse_snapshot AS SELECT * FROM horse_snapshots")\n'
    '            conn.commit()\n'
    '        finally:\n'
    '            conn.close()\n'
    '\n'
    '    def get(self, race_id: str) -> tuple[dict | None, int]:\n'
    '        conn = sqlite3.connect(self.path, timeout=2)\n'
    '        conn.row_factory = sqlite3.Row\n'
    '        try:\n'
    '            row = conn.execute("SELECT updated_at,payload FROM prepared_races WHERE race_id=?", (race_id,)).fetchone()\n'
    '            if not row:\n'
    '                return None, 0\n'
    '            try:\n'
    '                return json.loads(row["payload"]), int(row["updated_at"] or 0)\n'
    '            except Exception:\n'
    '                return None, 0\n'
    '        finally:\n'
    '            conn.close()\n'
    '\n'
    '    def put(self, detail: dict, force: bool = False) -> None:\n'
    '        race_id = str(detail.get("id") or "")\n'
    '        if not race_id:\n'
    '            return\n'
    '        if not _racedb_snapshot_usable(detail):\n'
    '            return\n'
    '        now = int(time.time())\n'
    '        detail.setdefault("preparedMeta", {})\n'
    '        revision_data={k:v for k,v in detail.items() if k!="preparedMeta"}\n'
    '        detail["preparedMeta"]["revision"]=hashlib.sha256(json.dumps(revision_data,sort_keys=True,ensure_ascii=False,default=str).encode()).hexdigest()[:24]\n'
    '        detail["preparedMeta"].update({\n'
    '            "build": "v87",\n'
    '            "prepared": True,\n'
    '            "preparedAtEpoch": now,\n'
    '            "metricsPrecomputed": True,\n'
    '        })\n'
    '        clean=_compact_display_snapshot(_strip_excluded(detail))\n'
    '        detail.clear();detail.update(clean)\n'
    '        payload = json.dumps(detail, ensure_ascii=False, separators=(",", ":"))\n'
    '        conn = sqlite3.connect(self.path, timeout=3)\n'
    '        try:\n'
    '            conn.execute("BEGIN IMMEDIATE")\n'
    '            old=conn.execute("SELECT payload FROM prepared_races WHERE race_id=?",(race_id,)).fetchone()\n'
    '            if old:\n'
    '                previous=json.loads(old[0])\n'
    '                if isinstance(previous.get("preRacePrediction"),dict) and (_prediction_clock_state(detail)[0]=="started" or not isinstance(detail.get("preRacePrediction"),dict)):\n'
    '                    detail["preRacePrediction"]=previous["preRacePrediction"]\n'
    '                    audit=_prediction_audit_from_lock(detail)\n'
    '                    if audit:detail["predictionAudit"]=audit\n'
    '                    payload=json.dumps(detail,ensure_ascii=False,separators=(",",":"))\n'
    '                prev_meta=previous.get("preparedMeta") or {}\n'
    '                prev_payouts=((previous.get("result") or {}).get("payouts") or [])\n'
    '                new_payouts=((detail.get("result") or {}).get("payouts") or [])\n'
    '                frozen=_snapshot_final(previous) or str(previous.get("date") or "")<_today_iso()\n'
    '                can_upgrade=bool(force or prev_meta.get("fastPartial") or (not prev_payouts and new_payouts))\n'
    '                if _racedb_snapshot_usable(previous) and frozen and not can_upgrade:\n'
    '                    detail.clear();detail.update(previous)\n'
    '                    return\n'
    '            conn.execute(\n'
    '                """\n'
    '                INSERT INTO prepared_races(race_id,race_date,circuit,updated_at,payload)\n'
    '                VALUES(?,?,?,?,?)\n'
    '                ON CONFLICT(race_id) DO UPDATE SET\n'
    '                    race_date=excluded.race_date,\n'
    '                    circuit=excluded.circuit,\n'
    '                    updated_at=excluded.updated_at,\n'
    '                    payload=excluded.payload\n'
    '                """,\n'
    '                (race_id, str(detail.get("date") or ""), str(detail.get("circuit") or ""), now, payload),\n'
    '            )\n'
    '            conn.execute("DELETE FROM horse_snapshots WHERE race_id=?",(race_id,))\n'
    '            conn.executemany("INSERT OR REPLACE INTO horse_snapshots(race_id,horse_no,payload) VALUES(?,?,?)",[(race_id,int(h.get("horseNumber") or 0),json.dumps(h,ensure_ascii=False)) for h in detail.get("horses",[])])\n'
    '            conn.commit()\n'
    '        finally:\n'
    '            conn.close()\n'
    '\n'
    '    def delete(self, race_id: str) -> None:\n'
    '        conn = sqlite3.connect(self.path, timeout=2)\n'
    '        try:\n'
    '            conn.execute("DELETE FROM prepared_races WHERE race_id=?", (race_id,))\n'
    '            conn.commit()\n'
    '        finally:\n'
    '            conn.close()\n'
    '\n'
    '    def status(self, race_date: str = "", circuit: str = "") -> dict:\n'
    '        conn = sqlite3.connect(self.path, timeout=2)\n'
    '        conn.row_factory = sqlite3.Row\n'
    '        try:\n'
    '            where=[]; args=[]\n'
    '            if race_date:\n'
    '                where.append("race_date=?"); args.append(race_date)\n'
    '            if circuit:\n'
    '                where.append("circuit=?"); args.append(circuit)\n'
    '            sql="SELECT COUNT(*) cnt, MAX(updated_at) last FROM prepared_races"\n'
    '            if where: sql += " WHERE " + " AND ".join(where)\n'
    '            row=conn.execute(sql,args).fetchone()\n'
    '            return {"count":int(row["cnt"] or 0),"last":int(row["last"] or 0)}\n'
    '        finally:\n'
    '            conn.close()\n'
    '\n'
    '\n'
    '# --- v86 RaceDB ---------------------------------------------------------\n'
    '# Normalized local data bank.  The UI can return a saved race immediately while\n'
    '# official/public sources refresh in the background.  RACEDB_PATH can point at a\n'
    '# persistent disk.  With the default /tmp path it still works as a fast cache but\n'
    '# will be rebuilt after an ephemeral host restart.\n'
    'class RaceDataBank:\n'
    '    def __init__(self, path: Path = RACEDB_PATH):\n'
    '        self.path = path\n'
    '        self.path.parent.mkdir(parents=True, exist_ok=True)\n'
    '        conn = sqlite3.connect(self.path, timeout=5)\n'
    '        try:\n'
    '            conn.execute("PRAGMA journal_mode=WAL")\n'
    '            conn.execute("PRAGMA synchronous=NORMAL")\n'
    '            conn.executescript(\n'
    '                """\n'
    '                CREATE TABLE IF NOT EXISTS race_snapshots (\n'
    '                    race_id TEXT PRIMARY KEY,\n'
    "                    race_date TEXT NOT NULL DEFAULT '',\n"
    "                    circuit TEXT NOT NULL DEFAULT '',\n"
    "                    track TEXT NOT NULL DEFAULT '',\n"
    '                    race_no INTEGER NOT NULL DEFAULT 0,\n'
    "                    title TEXT NOT NULL DEFAULT '',\n"
    "                    surface TEXT NOT NULL DEFAULT '',\n"
    '                    distance INTEGER NOT NULL DEFAULT 0,\n'
    "                    condition TEXT NOT NULL DEFAULT '',\n"
    "                    weather TEXT NOT NULL DEFAULT '',\n"
    "                    start_time TEXT NOT NULL DEFAULT '',\n"
    '                    updated_at INTEGER NOT NULL,\n'
    '                    payload TEXT NOT NULL\n'
    '                );\n'
    '                CREATE INDEX IF NOT EXISTS idx_racedb_races_date ON race_snapshots(race_date,circuit,track,race_no);\n'
    '\n'
    '                CREATE TABLE IF NOT EXISTS horse_master (\n'
    '                    horse_key TEXT PRIMARY KEY,\n'
    "                    name TEXT NOT NULL DEFAULT '',\n"
    "                    horse_external_id TEXT NOT NULL DEFAULT '',\n"
    "                    sex TEXT NOT NULL DEFAULT '',\n"
    '                    age INTEGER NOT NULL DEFAULT 0,\n'
    "                    birthday TEXT NOT NULL DEFAULT '',\n"
    "                    sire TEXT NOT NULL DEFAULT '',\n"
    "                    dam TEXT NOT NULL DEFAULT '',\n"
    "                    damsire TEXT NOT NULL DEFAULT '',\n"
    "                    trainer TEXT NOT NULL DEFAULT '',\n"
    "                    owner TEXT NOT NULL DEFAULT '',\n"
    "                    producer TEXT NOT NULL DEFAULT '',\n"
    '                    updated_at INTEGER NOT NULL,\n'
    "                    raw_json TEXT NOT NULL DEFAULT '{}'\n"
    '                );\n'
    '                CREATE INDEX IF NOT EXISTS idx_racedb_horse_name ON horse_master(name);\n'
    '\n'
    '                CREATE TABLE IF NOT EXISTS horse_entries (\n'
    '                    race_id TEXT NOT NULL,\n'
    '                    horse_no INTEGER NOT NULL,\n'
    "                    horse_key TEXT NOT NULL DEFAULT '',\n"
    '                    frame_no INTEGER NOT NULL DEFAULT 0,\n'
    "                    name TEXT NOT NULL DEFAULT '',\n"
    "                    jockey TEXT NOT NULL DEFAULT '',\n"
    "                    trainer TEXT NOT NULL DEFAULT '',\n"
    '                    carried_weight REAL,\n'
    '                    body_weight INTEGER,\n'
    '                    body_weight_change INTEGER,\n'
    '                    prize_money INTEGER NOT NULL DEFAULT 0,\n'
    '                    ten1f TEXT,\n'
    '                    ten TEXT,\n'
    '                    agari TEXT,\n'
    '                    estimated_popularity TEXT,\n'
    "                    pedigree_json TEXT NOT NULL DEFAULT '{}',\n"
    "                    style_json TEXT NOT NULL DEFAULT '{}',\n"
    "                    fit_json TEXT NOT NULL DEFAULT '{}',\n"
    "                    debut_json TEXT NOT NULL DEFAULT '{}',\n"
    "                    jump_json TEXT NOT NULL DEFAULT '{}',\n"
    "                    representative_json TEXT NOT NULL DEFAULT '{}',\n"
    '                    opponent_level REAL,\n'
    "                    metrics_json TEXT NOT NULL DEFAULT '{}',\n"
    "                    sources_json TEXT NOT NULL DEFAULT '[]',\n"
    '                    updated_at INTEGER NOT NULL,\n'
    "                    raw_json TEXT NOT NULL DEFAULT '{}',\n"
    '                    PRIMARY KEY(race_id,horse_no)\n'
    '                );\n'
    '                CREATE INDEX IF NOT EXISTS idx_racedb_entries_horse ON horse_entries(horse_key);\n'
    '\n'
    '                CREATE TABLE IF NOT EXISTS past_runs (\n'
    '                    horse_key TEXT NOT NULL,\n'
    '                    run_key TEXT NOT NULL,\n'
    "                    race_date TEXT NOT NULL DEFAULT '',\n"
    "                    track TEXT NOT NULL DEFAULT '',\n"
    "                    title TEXT NOT NULL DEFAULT '',\n"
    '                    distance INTEGER NOT NULL DEFAULT 0,\n'
    "                    surface TEXT NOT NULL DEFAULT '',\n"
    "                    condition TEXT NOT NULL DEFAULT '',\n"
    "                    weather TEXT NOT NULL DEFAULT '',\n"
    '                    finish INTEGER NOT NULL DEFAULT 0,\n'
    '                    time_seconds REAL,\n'
    '                    agari3f REAL,\n'
    '                    agari_rank INTEGER,\n'
    '                    frame_no INTEGER NOT NULL DEFAULT 0,\n'
    '                    horse_no INTEGER NOT NULL DEFAULT 0,\n'
    '                    carried_weight REAL,\n'
    "                    jockey TEXT NOT NULL DEFAULT '',\n"
    "                    corner_json TEXT NOT NULL DEFAULT '[]',\n"
    '                    opponent_level REAL,\n'
    '                    representative INTEGER NOT NULL DEFAULT 0,\n'
    "                    source TEXT NOT NULL DEFAULT '',\n"
    '                    updated_at INTEGER NOT NULL,\n'
    "                    raw_json TEXT NOT NULL DEFAULT '{}',\n"
    '                    PRIMARY KEY(horse_key,run_key)\n'
    '                );\n'
    '                CREATE INDEX IF NOT EXISTS idx_racedb_runs_date ON past_runs(horse_key,race_date DESC);\n'
    '                CREATE INDEX IF NOT EXISTS idx_racedb_runs_cutoff ON past_runs(race_date,jockey);\n'
    '                CREATE INDEX IF NOT EXISTS idx_racedb_runs_jockey ON past_runs(jockey,race_date);\n'
    '                CREATE INDEX IF NOT EXISTS idx_racedb_horse_sire ON horse_master(sire);\n'
    '                CREATE INDEX IF NOT EXISTS idx_racedb_runs_track_date ON past_runs(track,race_date);\n'
    '\n'
    '                CREATE TABLE IF NOT EXISTS odds_history (\n'
    '                    race_id TEXT NOT NULL,\n'
    '                    horse_no INTEGER NOT NULL,\n'
    '                    captured_at INTEGER NOT NULL,\n'
    '                    win_odds REAL,\n'
    '                    popularity INTEGER,\n'
    "                    source TEXT NOT NULL DEFAULT '',\n"
    "                    raw_json TEXT NOT NULL DEFAULT '{}',\n"
    '                    PRIMARY KEY(race_id,horse_no,captured_at)\n'
    '                );\n'
    '                CREATE INDEX IF NOT EXISTS idx_racedb_odds_race ON odds_history(race_id,captured_at DESC);\n'
    '\n'
    '                CREATE TABLE IF NOT EXISTS race_analysis (\n'
    '                    race_id TEXT PRIMARY KEY,\n'
    '                    updated_at INTEGER NOT NULL,\n'
    "                    scenario_json TEXT NOT NULL DEFAULT '{}',\n"
    "                    horse_diagnosis_json TEXT NOT NULL DEFAULT '[]',\n"
    "                    raw_json TEXT NOT NULL DEFAULT '{}'\n"
    '                );\n'
    '\n'
    '                CREATE TABLE IF NOT EXISTS source_state (\n'
    '                    source_key TEXT PRIMARY KEY,\n'
    '                    updated_at INTEGER NOT NULL,\n'
    "                    status TEXT NOT NULL DEFAULT '',\n"
    "                    note TEXT NOT NULL DEFAULT ''\n"
    '                );\n'
    '\n'
    '                CREATE TABLE IF NOT EXISTS field_state (\n'
    '                    race_id TEXT NOT NULL,\n'
    '                    field_key TEXT NOT NULL,\n'
    "                    status TEXT NOT NULL DEFAULT 'missing',\n"
    '                    completeness INTEGER NOT NULL DEFAULT 0,\n'
    "                    source TEXT NOT NULL DEFAULT '',\n"
    '                    updated_at INTEGER NOT NULL DEFAULT 0,\n'
    '                    last_attempt_at INTEGER NOT NULL DEFAULT 0,\n'
    '                    attempts INTEGER NOT NULL DEFAULT 0,\n'
    "                    note TEXT NOT NULL DEFAULT '',\n"
    "                    value_hash TEXT NOT NULL DEFAULT '',\n"
    '                    PRIMARY KEY(race_id,field_key)\n'
    '                );\n'
    '                CREATE INDEX IF NOT EXISTS idx_racedb_field_status ON field_state(status,updated_at);\n'
    '                CREATE INDEX IF NOT EXISTS idx_racedb_field_race ON field_state(race_id,field_key);\n'
    '\n'
    '                CREATE TABLE IF NOT EXISTS collector_runs (\n'
    '                    run_id TEXT PRIMARY KEY,\n'
    '                    race_id TEXT NOT NULL,\n'
    '                    started_at INTEGER NOT NULL,\n'
    '                    finished_at INTEGER NOT NULL DEFAULT 0,\n'
    "                    status TEXT NOT NULL DEFAULT '',\n"
    "                    attempted_fields TEXT NOT NULL DEFAULT '[]',\n"
    "                    before_json TEXT NOT NULL DEFAULT '{}',\n"
    "                    after_json TEXT NOT NULL DEFAULT '{}',\n"
    "                    note TEXT NOT NULL DEFAULT ''\n"
    '                );\n'
    '                CREATE INDEX IF NOT EXISTS idx_racedb_collector_race ON collector_runs(race_id,started_at DESC);\n'
    '                """\n'
    '            )\n'
    '            # v86 forward-compatible migration for an existing RaceDB.\n'
    '            # CR/share from v85 are intentionally no longer read or written.\n'
    '            def ensure_column(table: str, column: str, ddl: str) -> None:\n'
    '                cols={str(r[1]) for r in conn.execute(f"PRAGMA table_info({table})").fetchall()}\n'
    '                if column not in cols:\n'
    '                    conn.execute(f"ALTER TABLE {table} ADD COLUMN {column} {ddl}")\n'
    '            for col,ddl in (\n'
    '                ("style_json","TEXT NOT NULL DEFAULT \'{}\'"),("fit_json","TEXT NOT NULL DEFAULT \'{}\'"),\n'
    '                ("debut_json","TEXT NOT NULL DEFAULT \'{}\'"),("jump_json","TEXT NOT NULL DEFAULT \'{}\'"),\n'
    '                ("representative_json","TEXT NOT NULL DEFAULT \'{}\'"),("opponent_level","REAL")\n'
    '            ): ensure_column("horse_entries",col,ddl)\n'
    '            for col,ddl in (\n'
    '                ("agari3f","REAL"),("agari_rank","INTEGER"),("frame_no","INTEGER NOT NULL DEFAULT 0"),\n'
    '                ("horse_no","INTEGER NOT NULL DEFAULT 0"),("opponent_level","REAL"),("representative","INTEGER NOT NULL DEFAULT 0")\n'
    '            ): ensure_column("past_runs",col,ddl)\n'
    '            conn.commit()\n'
    '        finally:\n'
    '            conn.close()\n'
    '\n'
    '    @staticmethod\n'
    '    def _horse_key(h: dict) -> str:\n'
    '        ext=str(h.get("_jraHorseCname") or h.get("_netkeibaHorseId") or h.get("horseId") or "").strip()\n'
    '        if ext:return "id:"+ext\n'
    '        name=str(h.get("name") or "").strip()\n'
    '        return "name:"+name if name else ""\n'
    '\n'
    '    @staticmethod\n'
    '    def _run_key(rr: dict) -> str:\n'
    '        base="|".join(str(rr.get(k) or "") for k in ("raceId","date","track","title","distance","finish","timeSeconds"))\n'
    '        return hashlib.sha1(base.encode("utf-8","ignore")).hexdigest()\n'
    '\n'
    '    def upsert_race(self, detail: dict) -> None:\n'
    '        if not isinstance(detail,dict):return\n'
    '        race_id=str(detail.get("id") or "").strip()\n'
    '        if not race_id:return\n'
    '        now=int(time.time())\n'
    '        detail=_strip_excluded(detail)\n'
    '        conn=sqlite3.connect(self.path,timeout=5)\n'
    '        try:\n'
    '            conn.execute("PRAGMA journal_mode=WAL")\n'
    '            old=conn.execute("SELECT payload FROM race_snapshots WHERE race_id=?",(race_id,)).fetchone()\n'
    '            if old:\n'
    '                try:previous=json.loads(old[0])\n'
    '                except Exception:previous={}\n'
    '                if isinstance(previous.get("preRacePrediction"),dict) and (_prediction_clock_state(detail)[0]=="started" or not isinstance(detail.get("preRacePrediction"),dict)):\n'
    '                    detail["preRacePrediction"]=previous["preRacePrediction"]\n'
    '            snapshot_payload=_compact_display_snapshot(detail)\n'
    '            payload=json.dumps(snapshot_payload,ensure_ascii=False,separators=(",",":"),default=str)\n'
    '            conn.execute(\n'
    '                """INSERT INTO race_snapshots(race_id,race_date,circuit,track,race_no,title,surface,distance,condition,weather,start_time,updated_at,payload)\n'
    '                   VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?)\n'
    '                   ON CONFLICT(race_id) DO UPDATE SET race_date=excluded.race_date,circuit=excluded.circuit,track=excluded.track,\n'
    '                   race_no=excluded.race_no,title=excluded.title,surface=excluded.surface,distance=excluded.distance,condition=excluded.condition,\n'
    '                   weather=excluded.weather,start_time=excluded.start_time,updated_at=excluded.updated_at,payload=excluded.payload""",\n'
    '                (race_id,str(detail.get("date") or ""),str(detail.get("circuit") or ""),str(detail.get("track") or ""),int(detail.get("raceNumber") or 0),\n'
    '                 str(detail.get("title") or ""),str(detail.get("surface") or ""),int(detail.get("distance") or 0),str(detail.get("condition") or ""),\n'
    '                 str(detail.get("weather") or ""),str(detail.get("startTime") or ""),now,payload)\n'
    '            )\n'
    '            for h in detail.get("horses",[]) or []:\n'
    '                if not isinstance(h,dict):continue\n'
    '                no=int(h.get("horseNumber") or 0)\n'
    '                if no<=0:continue\n'
    '                hk=self._horse_key(h)\n'
    '                ped=h.get("pedigree") if isinstance(h.get("pedigree"),dict) else {}\n'
    '                smart=h.get("smartRc") if isinstance(h.get("smartRc"),dict) else {}\n'
    '                ext=str(h.get("_jraHorseCname") or h.get("_netkeibaHorseId") or h.get("horseId") or "")\n'
    '                conn.execute(\n'
    '                    """INSERT INTO horse_master(horse_key,name,horse_external_id,sex,age,birthday,sire,dam,damsire,trainer,owner,producer,updated_at,raw_json)\n'
    '                       VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?)\n'
    "                       ON CONFLICT(horse_key) DO UPDATE SET name=excluded.name,horse_external_id=CASE WHEN excluded.horse_external_id<>'' THEN excluded.horse_external_id ELSE horse_master.horse_external_id END,\n"
    "                       sex=CASE WHEN excluded.sex<>'' THEN excluded.sex ELSE horse_master.sex END,age=CASE WHEN excluded.age>0 THEN excluded.age ELSE horse_master.age END,\n"
    "                       birthday=CASE WHEN excluded.birthday<>'' THEN excluded.birthday ELSE horse_master.birthday END,sire=CASE WHEN excluded.sire<>'' THEN excluded.sire ELSE horse_master.sire END,\n"
    "                       dam=CASE WHEN excluded.dam<>'' THEN excluded.dam ELSE horse_master.dam END,damsire=CASE WHEN excluded.damsire<>'' THEN excluded.damsire ELSE horse_master.damsire END,\n"
    "                       trainer=CASE WHEN excluded.trainer<>'' THEN excluded.trainer ELSE horse_master.trainer END,owner=CASE WHEN excluded.owner<>'' THEN excluded.owner ELSE horse_master.owner END,\n"
    '                       producer=CASE WHEN excluded.producer<>\'\' THEN excluded.producer ELSE horse_master.producer END,updated_at=excluded.updated_at,raw_json=excluded.raw_json""",\n'
    '                    (hk,str(h.get("name") or ""),ext,str(h.get("sex") or ""),int(h.get("age") or 0),str(h.get("birthday") or ""),\n'
    '                     str(ped.get("sire") or ""),str(ped.get("dam") or ""),str(ped.get("damsire") or ped.get("damSire") or ""),str(h.get("trainer") or ""),\n'
    '                     str(h.get("owner") or ""),str(h.get("producer") or ""),now,json.dumps(h,ensure_ascii=False,separators=(",",":"),default=str))\n'
    '                )\n'
    '                conn.execute(\n'
    '                    """INSERT INTO horse_entries(race_id,horse_no,horse_key,frame_no,name,jockey,trainer,carried_weight,body_weight,body_weight_change,prize_money,\n'
    '                       ten1f,ten,agari,estimated_popularity,pedigree_json,style_json,fit_json,debut_json,jump_json,representative_json,opponent_level,metrics_json,sources_json,updated_at,raw_json)\n'
    '                       VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)\n'
    '                       ON CONFLICT(race_id,horse_no) DO UPDATE SET horse_key=excluded.horse_key,frame_no=excluded.frame_no,name=excluded.name,jockey=excluded.jockey,\n'
    '                       trainer=excluded.trainer,carried_weight=excluded.carried_weight,body_weight=excluded.body_weight,body_weight_change=excluded.body_weight_change,\n'
    '                       prize_money=excluded.prize_money,ten1f=COALESCE(excluded.ten1f,horse_entries.ten1f),ten=COALESCE(excluded.ten,horse_entries.ten),\n'
    '                       agari=COALESCE(excluded.agari,horse_entries.agari),estimated_popularity=COALESCE(excluded.estimated_popularity,horse_entries.estimated_popularity),\n'
    '                       pedigree_json=excluded.pedigree_json,style_json=excluded.style_json,fit_json=excluded.fit_json,debut_json=excluded.debut_json,\n'
    '                       jump_json=excluded.jump_json,representative_json=excluded.representative_json,opponent_level=excluded.opponent_level,\n'
    '                       metrics_json=excluded.metrics_json,sources_json=excluded.sources_json,updated_at=excluded.updated_at,raw_json=excluded.raw_json""",\n'
    '                    (race_id,no,hk,int(h.get("frameNumber") or 0),str(h.get("name") or ""),str(h.get("jockey") or ""),str(h.get("trainer") or ""),\n'
    '                     h.get("carriedWeight"),h.get("bodyWeight"),h.get("bodyWeightChange"),int(h.get("prizeMoneyAtRace") or 0),\n'
    '                     None if smart.get("ten1f") in (None,"") else str(smart.get("ten1f")),None if smart.get("ten") in (None,"") else str(smart.get("ten")),\n'
    '                     None if smart.get("agari") in (None,"") else str(smart.get("agari")),None if smart.get("estimatedPopularity") in (None,"") else str(smart.get("estimatedPopularity")),\n'
    '                     json.dumps(ped,ensure_ascii=False,separators=(",",":"),default=str),\n'
    '                     json.dumps((h.get("precomputedMetrics") or {}).get("style") or {},ensure_ascii=False,separators=(",",":"),default=str),\n'
    '                     json.dumps((h.get("precomputedMetrics") or {}).get("fit") or {},ensure_ascii=False,separators=(",",":"),default=str),\n'
    '                     json.dumps({"isDebut":bool(h.get("debutNoHistory")),"analysisMode":detail.get("analysisMode")},ensure_ascii=False,separators=(",",":")),\n'
    '                     json.dumps(h.get("jumpStats") or h.get("obstacleStats") or {},ensure_ascii=False,separators=(",",":"),default=str),\n'
    '                     json.dumps(h.get("representativeRun") or {},ensure_ascii=False,separators=(",",":"),default=str),\n'
    '                     (h.get("precomputedMetrics") or {}).get("fit",{}).get("level"),\n'
    '                     json.dumps(h.get("precomputedMetrics") or {},ensure_ascii=False,separators=(",",":"),default=str),\n'
    '                     json.dumps(detail.get("dataSources") or [],ensure_ascii=False,separators=(",",":"),default=str),now,json.dumps(h,ensure_ascii=False,separators=(",",":"),default=str))\n'
    '                )\n'
    '                for rr in (h.get("allPastRuns") or h.get("recentRaces") or []):\n'
    '                    if not isinstance(rr,dict):continue\n'
    '                    rk=self._run_key(rr)\n'
    '                    conn.execute(\n'
    '                        """INSERT INTO past_runs(horse_key,run_key,race_date,track,title,distance,surface,condition,weather,finish,time_seconds,agari3f,agari_rank,frame_no,horse_no,carried_weight,jockey,corner_json,opponent_level,representative,source,updated_at,raw_json)\n'
    '                           VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)\n'
    '                           ON CONFLICT(horse_key,run_key) DO UPDATE SET updated_at=excluded.updated_at,raw_json=excluded.raw_json,\n'
    '                           agari3f=COALESCE(excluded.agari3f,past_runs.agari3f),agari_rank=COALESCE(excluded.agari_rank,past_runs.agari_rank),\n'
    '                           opponent_level=COALESCE(excluded.opponent_level,past_runs.opponent_level),representative=MAX(past_runs.representative,excluded.representative)""",\n'
    '                        (hk,rk,str(rr.get("date") or ""),str(rr.get("track") or ""),str(rr.get("title") or ""),int(rr.get("distance") or 0),str(rr.get("surface") or ""),\n'
    '                         str(rr.get("condition") or ""),str(rr.get("weather") or ""),int(rr.get("finish") or 0),rr.get("timeSeconds"),rr.get("agari3f") or rr.get("agari"),\n'
    '                         rr.get("agariRank") or rr.get("agari_rank"),int(rr.get("frameNumber") or 0),int(rr.get("horseNumber") or 0),rr.get("carriedWeight"),str(rr.get("jockey") or ""),\n'
    '                         json.dumps(rr.get("cornerPositions") or [],ensure_ascii=False,separators=(",",":")),rr.get("opponentLevel"),1 if rr.get("representative") else 0,\n'
    '                         str(rr.get("source") or ""),now,json.dumps(rr,ensure_ascii=False,separators=(",",":"),default=str))\n'
    '                    )\n'
    '            conn.commit()\n'
    '        finally:\n'
    '            conn.close()\n'
    '\n'
    '    def get_race(self, race_id: str) -> tuple[dict | None,int]:\n'
    '        conn=sqlite3.connect(self.path,timeout=2);conn.row_factory=sqlite3.Row\n'
    '        try:\n'
    '            row=conn.execute("SELECT updated_at,payload FROM race_snapshots WHERE race_id=?",(race_id,)).fetchone()\n'
    '            if not row:return None,0\n'
    '            try:return json.loads(row["payload"]),int(row["updated_at"] or 0)\n'
    '            except Exception:return None,0\n'
    '        finally:conn.close()\n'
    '\n'
    '    def upsert_past_runs(self, horse: dict, runs: list[dict]) -> int:\n'
    '        if not isinstance(horse,dict) or not runs:return 0\n'
    '        hk=self._horse_key(horse)\n'
    '        if not hk:return 0\n'
    '        now=int(time.time());count=0\n'
    '        conn=sqlite3.connect(self.path,timeout=5)\n'
    '        try:\n'
    '            for rr in runs:\n'
    '                if not isinstance(rr,dict):continue\n'
    '                rr=_strip_excluded(rr)\n'
    '                rk=self._run_key(rr)\n'
    '                conn.execute(\n'
    '                    """INSERT INTO past_runs(horse_key,run_key,race_date,track,title,distance,surface,condition,weather,finish,time_seconds,agari3f,agari_rank,frame_no,horse_no,carried_weight,jockey,corner_json,opponent_level,representative,source,updated_at,raw_json)\n'
    '                       VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)\n'
    '                       ON CONFLICT(horse_key,run_key) DO UPDATE SET updated_at=excluded.updated_at,raw_json=excluded.raw_json,\n'
    '                       agari3f=COALESCE(excluded.agari3f,past_runs.agari3f),agari_rank=COALESCE(excluded.agari_rank,past_runs.agari_rank),\n'
    '                       opponent_level=COALESCE(excluded.opponent_level,past_runs.opponent_level),representative=MAX(past_runs.representative,excluded.representative)""",\n'
    '                    (hk,rk,str(rr.get("date") or ""),str(rr.get("track") or ""),str(rr.get("title") or ""),int(rr.get("distance") or 0),str(rr.get("surface") or ""),\n'
    '                     str(rr.get("condition") or ""),str(rr.get("weather") or ""),int(rr.get("finish") or 0),rr.get("timeSeconds"),rr.get("agari3f") or rr.get("agari"),\n'
    '                     rr.get("agariRank") or rr.get("agari_rank"),int(rr.get("frameNumber") or 0),int(rr.get("horseNumber") or 0),rr.get("carriedWeight"),str(rr.get("jockey") or ""),\n'
    '                     json.dumps(rr.get("cornerPositions") or [],ensure_ascii=False,separators=(",",":")),rr.get("opponentLevel"),1 if rr.get("representative") else 0,\n'
    '                     str(rr.get("source") or ""),now,json.dumps(rr,ensure_ascii=False,separators=(",",":"),default=str)))\n'
    '                count+=1\n'
    '            conn.commit();return count\n'
    '        finally:conn.close()\n'
    '\n'
    '    def source_updated(self, source_key: str) -> int:\n'
    '        conn=sqlite3.connect(self.path,timeout=2);conn.row_factory=sqlite3.Row\n'
    '        try:\n'
    '            row=conn.execute("SELECT updated_at FROM source_state WHERE source_key=?",(source_key,)).fetchone()\n'
    '            return int(row["updated_at"] or 0) if row else 0\n'
    '        finally:conn.close()\n'
    '\n'
    '    def mark_source(self, source_key: str, status: str = "done", note: str = "") -> None:\n'
    '        conn=sqlite3.connect(self.path,timeout=2)\n'
    '        try:\n'
    '            conn.execute("INSERT INTO source_state(source_key,updated_at,status,note) VALUES(?,?,?,?) ON CONFLICT(source_key) DO UPDATE SET updated_at=excluded.updated_at,status=excluded.status,note=excluded.note",\n'
    '                         (source_key,int(time.time()),status,note[:500]))\n'
    '            conn.commit()\n'
    '        finally:conn.close()\n'
    '\n'
    '    def save_odds(self, race_id: str, rows: list[dict], source: str = "", captured_at: int | None = None) -> int:\n'
    '        if not rows:return 0\n'
    '        # Round to 15 seconds so a polling burst cannot create pointless duplicates.\n'
    '        ts=int(captured_at or time.time());ts=ts-(ts%15)\n'
    '        conn=sqlite3.connect(self.path,timeout=3);count=0\n'
    '        try:\n'
    '            for z in rows:\n'
    '                z=_strip_excluded(z)\n'
    '                try:no=int(z.get("horseNumber") or 0)\n'
    '                except Exception:no=0\n'
    '                if no<=0:continue\n'
    '                try:wo=float(z.get("winOdds")) if z.get("winOdds") not in (None,"") else None\n'
    '                except Exception:wo=None\n'
    '                try:pop=int(z.get("popularity")) if z.get("popularity") not in (None,"") else None\n'
    '                except Exception:pop=None\n'
    '                conn.execute("INSERT OR REPLACE INTO odds_history(race_id,horse_no,captured_at,win_odds,popularity,source,raw_json) VALUES(?,?,?,?,?,?,?)",\n'
    '                             (race_id,no,ts,wo,pop,str(source or z.get("oddsSource") or ""),json.dumps(z,ensure_ascii=False,separators=(",",":"),default=str)))\n'
    '                count+=1\n'
    '            conn.commit();return count\n'
    '        finally:conn.close()\n'
    '\n'
    '    def odds_latest(self, race_id: str) -> list[dict]:\n'
    '        conn=sqlite3.connect(self.path,timeout=2);conn.row_factory=sqlite3.Row\n'
    '        try:\n'
    '            rows=conn.execute("""SELECT o.* FROM odds_history o JOIN (SELECT horse_no,MAX(captured_at) t FROM odds_history WHERE race_id=? GROUP BY horse_no) x\n'
    '                                 ON o.horse_no=x.horse_no AND o.captured_at=x.t WHERE o.race_id=? ORDER BY o.horse_no""",(race_id,race_id)).fetchall()\n'
    '            return [{"horseNumber":int(r["horse_no"]),"winOdds":r["win_odds"],"popularity":r["popularity"],"oddsSource":r["source"],"capturedAt":int(r["captured_at"])} for r in rows]\n'
    '        finally:conn.close()\n'
    '\n'
    '    def save_analysis(self, race_id: str, payload: dict) -> None:\n'
    '        if not race_id or not isinstance(payload,dict):return\n'
    '        payload=_strip_excluded(payload)\n'
    '        scenarios=payload.get("scenarios") or {}\n'
    '        horses=payload.get("horses") or []\n'
    '        now=int(time.time())\n'
    '        conn=sqlite3.connect(self.path,timeout=3)\n'
    '        try:\n'
    '            conn.execute("INSERT INTO race_analysis(race_id,updated_at,scenario_json,horse_diagnosis_json,raw_json) VALUES(?,?,?,?,?) ON CONFLICT(race_id) DO UPDATE SET updated_at=excluded.updated_at,scenario_json=excluded.scenario_json,horse_diagnosis_json=excluded.horse_diagnosis_json,raw_json=excluded.raw_json",\n'
    '                         (race_id,now,json.dumps(scenarios,ensure_ascii=False,separators=(",",":"),default=str),json.dumps(horses,ensure_ascii=False,separators=(",",":"),default=str),json.dumps(payload,ensure_ascii=False,separators=(",",":"),default=str)))\n'
    '            conn.commit()\n'
    '        finally:conn.close()\n'
    '\n'
    '    def get_analysis(self, race_id: str) -> dict | None:\n'
    '        conn=sqlite3.connect(self.path,timeout=2);conn.row_factory=sqlite3.Row\n'
    '        try:\n'
    '            row=conn.execute("SELECT raw_json FROM race_analysis WHERE race_id=?",(race_id,)).fetchone()\n'
    '            return json.loads(row["raw_json"]) if row else None\n'
    '        except Exception:return None\n'
    '        finally:conn.close()\n'
    '\n'
    '    def status(self, race_date: str = "", circuit: str = "") -> dict:\n'
    '        conn=sqlite3.connect(self.path,timeout=2);conn.row_factory=sqlite3.Row\n'
    '        try:\n'
    '            where=[];args=[]\n'
    '            if race_date:where.append("race_date=?");args.append(race_date)\n'
    '            if circuit:where.append("circuit=?");args.append(circuit)\n'
    '            sql="SELECT COUNT(*) cnt,MAX(updated_at) last FROM race_snapshots"+(" WHERE "+" AND ".join(where) if where else "")\n'
    '            rr=conn.execute(sql,args).fetchone();hm=conn.execute("SELECT COUNT(*) c FROM horse_master").fetchone();pr=conn.execute("SELECT COUNT(*) c FROM past_runs").fetchone();od=conn.execute("SELECT COUNT(*) c FROM odds_history").fetchone();an=conn.execute("SELECT COUNT(*) c FROM race_analysis").fetchone()\n'
    '            return {"races":int(rr["cnt"] or 0),"last":int(rr["last"] or 0),"horses":int(hm["c"] or 0),"pastRuns":int(pr["c"] or 0),"oddsPoints":int(od["c"] or 0),"analyses":int(an["c"] or 0),"path":str(self.path)}\n'
    '        finally:conn.close()\n'
)

def install_race_stores(namespace: dict) -> None:
    code = compile(SOURCE, '<arvexq:race_stores>', 'exec')
    exec(code, namespace, namespace)
